
from time import sleep
from botfunctions import*
repetidor = 50

while repetidor > 0:

    loginaccount1()
    loginaccount2()
    loginaccount3()
    puttingherotowork1()
    puttingherotowork2()
    puttingherotowork3()
    sleep(135)
    entryandgoout1()
    entryandgoout2()
    entryandgoout3()
    sleep(135)
    entryandgoout1()
    entryandgoout2()
    entryandgoout3()
    sleep(135)
    entryandgoout1()
    entryandgoout2()
    entryandgoout3()
    sleep(135)
    entryandgoout1()
    entryandgoout2()
    entryandgoout3()
    sleep(135)
    entryandgoout1()
    entryandgoout2()
    entryandgoout3()
    sleep(135)
    entryandgoout1()
    entryandgoout2()
    entryandgoout3()
    sleep(135)
    entryandgoout1()
    entryandgoout2()
    entryandgoout3()
    sleep(135)
    entryandgoout1()
    entryandgoout2()
    entryandgoout3()
    sleep(135)
    entryandgoout1()
    entryandgoout2()
    entryandgoout3()
    sleep(135)
    entryandgoout1()
    entryandgoout2()
    entryandgoout3()

    repetidor = repetidor-1
